### ISSUE TITLE
Swagger Integration with Serverless

### ISSUE THREAD

**Issue by sid88in** [serverless/serverless-graphql-apollo#123]
In AWS CF we can integrate swagger api using this:
```
Resources:
  MyRestApi:
  Type: AWS::ApiGateway::RestApi
  Properties:
    Body:
```
1. How can we integrate the same in serverless? Any example? 
2. How can we simulate API Gateway locally using serverless offline? Any serverless plugin? My swagger api has a proxy for dynamodb.
